spring.application.name=ai-invoice-processing
spring.datasource.url=jdbc:postgresql://localhost:5432/invoice_processing
spring.datasource.username=invoice_app
spring.datasource.password=invoice_app

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true